// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrtciuqexgybunnfjzsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydGNpdXFleGd5YnVubmZqenNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODc0MDksImV4cCI6MjA2ODE2MzQwOX0.Bj9sTIfnG69GGZLmmK3bHlA7vPHOSGd9hZ9KpZEjjUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});